server.port=8081

# RabbitMQ connection settings for Assignment 2 Part 1
chat.rabbitmq.host=localhost
chat.rabbitmq.port=5672
chat.rabbitmq.username=guest
chat.rabbitmq.password=guest
chat.rabbitmq.exchange=chat.exchange
chat.rabbitmq.channelPoolSize=16

chat.serverId=server-v2

