server.port=8082

chat.rabbitmq.host=localhost
chat.rabbitmq.port=5672
chat.rabbitmq.username=guest
chat.rabbitmq.password=guest

# Consumer threading configuration
chat.consumer.threadCount=10
chat.consumer.prefetch=50

